import multiprocessing
import time
import html



class fucker():
    results = []
    @staticmethod
    def funct(a):
        print("processing", a)
        time.sleep(2)
        return [a, a ** 2]

    def handler(self, result):
        print("result from {} is {}".format(result[0], result[1]))
        self.results.append(result[1])


if __name__ == '__main__':
    # pool = multiprocessing.Pool()
    #
    # # multiprocessing.freeze_support()
    # a = fucker()
    # a.funct(5555)
    # for x in range(50):
    #     pool.apply_async(a.funct, (x,), callback=lambda x: a.handler(x))
    #
    # # pool.map_async(a.funct, [x for x in range(50)], callback=)
    #
    # pool.close()
    # pool.join()
    # print(results)
    # print(multiprocessing.cpu_count())
   print("""b'06-24 23:09:36.618  6601  6676 I python  : ERROR:root:code for hash blake2b was not found.\n'b'06-24 23:09:36.618  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.618  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.618  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.618  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.618  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.618  6601  6676 I python  : ValueError: unsupported hash type blake2b\n06-24 23:09:36.620  6601  6676 I python  : ERROR:root:code for hash blake2s was not found.\n06-24 23:09:36.620  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.620  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.620  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.620  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.620  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.620  6601  6676 I python  : ValueError: unsupported hash type blake2s\n06-24 23:09:36.621  6601  6676 I python  : ERROR:root:code for hash sha3_224 was not found.\n06-24 23:09:36.621  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.621  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.621  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.621  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.621  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.621  6601  6676 I python  : ValueError: unsupported hash type sha3_224\n06-24 23:09:36.622  6601  6676 I python  : ERROR:root:code for hash sha3_256 was not found.\n06-24 23:09:36.622  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.622  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.622  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.622  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.622  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.622  6601  6676 I python  : ValueError: unsupported hash type sha3_256\n06-24 23:09:36.623  6601  6676 I python  : ERROR:root:code for hash sha3_384 was not found.\n06-24 23:09:36.623  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.623  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.623  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.624  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.624  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.624  6601  6676 I python  : ValueError: unsupported hash type sha3_384\n06-24 23:09:36.625  6601  6676 I python  : ERROR:root:code for hash sha3_512 was not found.\n06-24 23:09:36.625  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.625  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <modu'b'le>\n06-24 23:09:36.625  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.625  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.625  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.625  6601  6676 I python  : ValueError: unsupported hash type sha3_512\n06-24 23:09:36.626  6601  6676 I python  : ERROR:root:code for hash shake_128 was not found.\n06-24 23:09:36.626  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.626  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.626  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.626  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.626  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.626  6601  6676 I python  : ValueError: unsupported hash type shake_128\n06-24 23:09:36.627  6601  6676 I python  : ERROR:root:code for hash shake_256 was not found.\n06-24 23:09:36.627  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:36.627  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:36.627  6601  6676 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:36.627  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:36.627  6601  6676 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:36.627  6601  6676 I python  : ValueError: unsupported hash type shake_256\n'b'06-24 23:09:38.781  6601  6676 I python  : Traceback (most recent call last):\n06-24 23:09:38.781  6601  6676 I python  :   File "main.py", line 18, in <module>\n'b'06-24 23:09:38.782  6601  6676 I python  :     import html5lib\n06-24 23:09:38.782  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/site-packages/html5lib/__init__.py", line 25, in <module>\n06-24 23:09:38.782  6601  6676 I python  :     from .html5parser import HTMLParser, parse, parseFragment\n06-24 23:09:38.782  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/site-packages/html5lib/html5parser.py", line 7, in <module>\n06-24 23:09:38.783  6601  6676 I python  :     from . import _inputstream\n06-24 23:09:38.783  6601  6676 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/site-packages/html5lib/_inputstream.py", line 9, in <module>\n06-24 23:09:38.783  6601  6676 I python  :     import webencodings\n06-24 23:09:38.783  6601  6676 I python  : ModuleNotFoundError: No module named \'webencodings\'\n'b'06-24 23:09:38.839  6601  6676 I python  : Python for android ended.\n'b'06-24 23:09:51.134  6826  6847 I python  : Initialize Python for Android\n06-24 23:09:51.134  6826  6847 I python  : Changing directory to the one provided by ANDROID_ARGUMENT\n06-24 23:09:51.134  6826  6847 I python  : /data/user/0/com.whalebayco.wbc/files/app\n06-24 23:09:51.134  6826  6847 I python  : Preparing to initialize python\n'b'06-24 23:09:51.135  6826  6847 I python  : crystax_python exists\n06-24 23:09:51.136  6826  6847 I python  : calculated paths to be...\n06-24 23:09:51.136  6826  6847 I python  : /data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip:/data/user/0/com.whalebayco.wbc/files/app/crystax_python/modules\n06-24 23:09:51.136  6826  6847 I python  : set wchar paths...\n'b'06-24 23:09:51.349  6826  6847 I python  : Initialized python\n06-24 23:09:51.350  6826  6847 I python  : AND: Init threads\n'b"06-24 23:09:51.350  6826  6847 I python  : testing python print redirection\n06-24 23:09:51.351  6826  6847 I python  : Android path ['.', '/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip', '/data/user/0/com.whalebayco.wbc/files/app/crystax_python/modules', '/data/user/0/com.whalebayco.wbc/files/app/crystax_python/site-packages']\n06-24 23:09:51.351  6826  6847 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin', 'DOWNLOAD_CACHE': '/data/cache', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/QPerformance.jar:/system/framework/SmpsManager.jar:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/legacy-test.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/smartbondingservice.jar:/system/framework/sprengine.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/timakeystore.jar:/system/framework/fipstimakeystore.jar:/system/framework/ucmopensslenginehelper.jar:/system/framework/esecomm.jar:/system/framework/SemAudioThumbnail.jar:/system/framework/knoxsdk.jar:/system/framework/sec_edm.jar:/system/framework/sagearpolicymanager.jar:/system/framework/sec_sdp_sdk.jar:/system/framework/sec_sdp_hidden_sdk.jar:/system/framework/knoxvpnuidtag.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar:/system/framework/WfdCommon.jar:/system/framework/oem-services.jar:/system/framework/qcom.fmradio.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/samsung-services.jar:/system/framework/hqm.jar:/system/framework/dmf.jar:/system/framework/ssrm.jar', 'MC_AUTH_TOKEN_PATH': '/efs/TEE', 'KNOX_STORAGE': '/data/knox/ext_sdcard', 'ENC_EMULATED_STORAGE_TARGET': '/storage/enc_emulated', 'ANDROID_SOCKET_zygote_secondary': '8', 'ANDROID_ENTRYPOINT': 'main.pyo', 'ANDROID_ARGUMENT': '/data/user/0/com.whalebayco.wbc/files/app', 'ANDROID_APP_PATH': '/data/user/0/com.whalebayco.wbc/files/app', 'ANDROID_PRIVATE': '/data/user/0/com.whalebayco.wbc/files', 'ANDROID_UNPACK': '/data/user/0/com.whalebayco.wbc/files/app', 'PYTHONHOME': '/data/user/0/com.whalebayco.wbc/files/app', 'PYTHONPATH': '/data/user/0/com.whalebayco.wbc/files/app:/data/user/0/com.whalebayco.wbc/files/app/lib', 'PYTHONOPTIMIZE': '2', 'PYTHON_NAME': 'python'})\n06-24 23:09:51.352  6826  6847 I python  : Android kivy bootstrap done. __name__ is __main__\n06-24 23:09:51.352  6826  6847 I python  : AND: Ran string\n06-24 23:09:51.352  6826  6847 I python  : Run user program, change dir and execute entrypoint\n06-24 23:09:51.352  6826  6847 I python  : main.py\n"b'06-24 23:09:52.015  6826  6847 I python  : ERROR:root:code for hash blake2b was not found.\n'b'06-24 23:09:52.015  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.015  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.015  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.015  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.015  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.015  6826  6847 I python  : ValueError: unsupported hash type blake2b\n06-24 23:09:52.016  6826  6847 I python  : ERROR:root:code for hash blake2s was not found.\n06-24 23:09:52.017  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.017  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.017  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.017  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.017  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.017  6826  6847 I python  : ValueError: unsupported hash type blake2s\n06-24 23:09:52.018  6826  6847 I python  : ERROR:root:code for hash sha3_224 was not found.\n06-24 23:09:52.018  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.018  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.018  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.018  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.018  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.018  6826  6847 I python  : ValueError: unsupported hash type sha3_224\n06-24 23:09:52.020  6826  6847 I python  : ERROR:root:code for hash sha3_256 was not found.\n06-24 23:09:52.020  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.020  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.020  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.020  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.020  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.020  6826  6847 I python  : ValueError: unsupported hash type sha3_256\n06-24 23:09:52.021  6826  6847 I python  : ERROR:root:code for hash sha3_384 was not found.\n06-24 23:09:52.021  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.021  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.021  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.021  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.021  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.021  6826  6847 I python  : ValueError: unsupported hash type sha3_384\n06-24 23:09:52.022  6826  6847 I python  : ERROR:root:code for hash sha3_512 was not found.\n06-24 23:09:52.023  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.023  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <modu'b'le>\n06-24 23:09:52.023  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.023  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.023  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.023  6826  6847 I python  : ValueError: unsupported hash type sha3_512\n06-24 23:09:52.024  6826  6847 I python  : ERROR:root:code for hash shake_128 was not found.\n06-24 23:09:52.024  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.024  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.024  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.024  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.024  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.024  6826  6847 I python  : ValueError: unsupported hash type shake_128\n06-24 23:09:52.025  6826  6847 I python  : ERROR:root:code for hash shake_256 was not found.\n06-24 23:09:52.025  6826  6847 I python  : Traceback (most recent call last):\n06-24 23:09:52.025  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>\n06-24 23:09:52.026  6826  6847 I python  :     globals()[__func_name] = __get_hash(__func_name)\n06-24 23:09:52.026  6826  6847 I python  :   File "/data/user/0/com.whalebayco.wbc/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor\n06-24 23:09:52.026  6826  6847 I python  :     raise ValueError(\'unsupported hash type \' + name)\n06-24 23:09:52.026  6826  6847 I python  : ValueError: unsupported hash type shake_256\n'
""")